global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "uptime-kuma"
    scrape_interval: 30s
    scheme: https
    static_configs:
      - targets: ["uptime-kuma-monitor.up.railway.app"]
    basic_auth:
      password: $UPTIME_KUMA_PASSWORD

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['$YOUR_SERVICE_URL']
  #   basic_auth:
  #     username: $HTTP_AUTH_USERNAME
  #     password: $HTTP_AUTH_PASSWORD